"""Report writers for ad_engine.py: drafts/<service>.md, ads_proposed.json and the three STEP 8 reports."""
from __future__ import annotations

import json
from pathlib import Path

from bazaraki_agent import ad_engine as ae

ORDER = ["new-build", "extensions", "structural", "full-renovation", "bathroom", "kitchen", "ceilings", "partitions", "painting",
         "tiling", "waterproofing", "remote-owner", "repairs", "pool-care", "pool-renovation", "concrete-repairs", "retaining-walls",
         "damp-repairs", "etics", "joinery", "electrical", "light-steel"]


def _w(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(text.encode("utf-8"))


def write_all(result, services, official):
    ads = sorted(result["ads"], key=lambda a: ORDER.index(a["service_key"]) if a["service_key"] in ORDER else 99)
    for a in ads:
        s = services[a["service_key"]]
        L = [f"# Ad draft: {a['service_key']}", "", f"**Status:** `{a['status']}` · category {s['bazaraki_category'].get('rubric_id')} · "
             f"location {s['locations']['xml_district_id']} · generated by `ad_engine.py` (2026-10-03). **Not published.**", ""]
        if not a.get("description"):
            L += ["No ad text written.", "", *[f"- {p}" for p in a["problems"]]]
            _w(ae.ADS / "drafts" / f"{a['service_key']}.md", "\n".join(L) + "\n"); continue
        L += [f"**Title (XML, EN):** {a['title_en']}  ({len(a['title_en'])} chars)", f"**Greek title (first line of the description):** {a['title_el']}", "",
              f"**Price:** {a['price_meta'].get('display_en') or 'research required: no price in the ad'}", "",
              f"**Photos:** {len(a['images'])} ({a['photo_counts'].get('proposed', 0)} proposed, {a['photo_counts'].get('approved', 0)} approved; "
              f"{a['photo_counts'].get('stock', 0)} stock, illustrative)", ""]
        for i, p in enumerate(a["images"], 1):
            L.append(f"{i}. `{Path(p['file']).name}` · {p['source']} · {p['source_url']} · {p['status']}")
        L += ["", "**Problems:** " + ("none" if not a["problems"] else ""), *[f"- {p}" for p in a["problems"]], ""]
        if a.get("live_conflicts"):
            L += ["**Live ads of this service (must be deactivated before this ad is published, wave 3):**",
                  *[f"- {lid} \"{t}\" (title similarity {j})" for lid, t, j in a["live_conflicts"]], ""]
        L += ["## Description (exact text, Greek first)", "", "```text", a["description"], "```", "",
              f"Description length: {len(a['description'])} / {ae.MAX_DESCRIPTION} characters."]
        _w(ae.ADS / "drafts" / f"{a['service_key']}.md", "\n".join(L) + "\n")

    # hospitality variants: separate drafts, never published together with the main ad (D-046)
    for v in result.get("variants", []):
        L = [f"# Hospitality variant (draft): {v['service_key']}", "", f"**Status:** `{v['status']}` · publish false · variant of the main ad "
             f"`{v['service_key']}`. **Never publish both** (same service = duplicate).", ""]
        if not v.get("description"):
            L += [*[f"- {p}" for p in v["problems"]]]
        else:
            L += [f"**Title (EN):** {v['title_en']} ({len(v['title_en'])} chars)", f"**Greek title:** {v['title_el']}", "",
                  "**Problems:** " + ("none" if not v["problems"] else ""), *[f"- {p}" for p in v["problems"]], "",
                  "```text", v["description"], "```"]
        _w(ae.ADS / "hospitality_drafts" / f"{v['service_key']}.md", "\n".join(L) + "\n")
    _w(ae.ADS / "hospitality_variants.json", json.dumps([{k: v.get(k) for k in ("service_key", "variant_of", "status", "publish", "title_en",
       "title_el", "description", "problems")} for v in result.get("variants", [])], ensure_ascii=False, indent=2) + "\n")

    # machine-readable output for STEP 10 (still drafts: publish false)
    out = [{k: a.get(k) for k in ("service_key", "status", "title_en", "title_el", "description", "rubric", "district", "attrs", "problems")}
           | {"images": [{"file": p["file"], "source": p["source"], "source_url": p["source_url"], "status": p["status"]} for p in a.get("images", [])],
              "price_display_en": a.get("price_meta", {}).get("display_en"), "publish": False,
              **({"layout": a["layout"], "review_only": True, "sections": a["sections"], "fee_scope": a.get("fee_scope"),
                  "quality_passed": a.get("quality_passed", False)} if a.get("layout") else {})} for a in ads]
    _w(ae.ADS / "ads_proposed.json", json.dumps(out, ensure_ascii=False, indent=2) + "\n")

    # ADS_REVIEW_REPORT.md
    R = ["# Ads review report (STEP 8, 2026-10-03)", "",
         "Statuses: `ready_to_review` = price approved, at least 5 proposed photos, 0 problems · `draft` = research-required price or fewer than 5 photos · "
         "`blocked` = owner hold or problems · `ready_to_publish` needs 5 photos approved individually (none yet).", "",
         "| # | Service | Status | EN title | Greek title | Photos | Problems |", "|---|---|---|---|---|---|---|"]
    for i, a in enumerate(ads, 1):
        R.append(f"| {i} | {a['service_key']} | {a['status']} | {a['title_en'] or '—'} | {a['title_el'] or '—'} | {len(a.get('images', []))} | "
                 f"{len(a['problems'])} |")
    R += ["", "## Problems", ""] + [f"- **{a['service_key']}**: {p}" for a in ads for p in a["problems"]] + ["", "Drafts: `master_plan/ads/drafts/`."]
    _w(ae.ADS / "ADS_REVIEW_REPORT.md", "\n".join(R) + "\n")

    # BAZARAKI_COMPLIANCE_CHECK.md
    C = ["# Bazaraki compliance check (STEP 8, 2026-10-03)", "",
         "**Official source first:** https://www.bazaraki.com/business-xml-guide/. It was read live on 2026-10-03 and compared with the saved copies "
         "(`official-docs/Bazaraki XML Format.docx`, `business-xml-guide.docx`, `feed-repo/bazaraki_agent/data/bazaraki_official_list.txt`). "
         "**No change found:** the stop-word list is identical (23 words, EN + GR).", "",
         "| Rule | Source | Applied |", "|---|---|---|",
         "| Title: text and digits only, max 70 chars | OFFICIAL | `_title_problems` (allowed: letters, digits, space , . - ') |",
         f"| Title stop words ({len(official['stopwords'])}, EN + GR) | OFFICIAL | `stopword_hits` on the EN and Greek titles |",
         "| No doubled words in title (\"Nicosia Nicosia\") | OFFICIAL | yes; INTERNAL: no repeated content word at all |",
         "| No price in title | OFFICIAL | `PRICE_IN_TITLE` + no € |",
         "| Description max 10,000 chars; escape ' \" & < > ; no CDATA/HTML | OFFICIAL | length check here; escaping in `feed.py` |",
         "| 0–16 images, JPG/PNG; new URL needed to change a photo | OFFICIAL | max 16 here; formats in the photo pipeline + validate.py |",
         "| One rubric and one district per ad, official IDs | OFFICIAL | registry + catalog_proposed (IDs validated) |",
         "| Required attrs per category: Property-maintenance categories need `language` (10 Greek, 20 English, 30 German, 40 Russian, 50 Romanian, 60 Bulgarian) = **languages the service is offered in** | OFFICIAL (live guide per rubric, checked for 2167, 311, 312, 314, 317, 331, 3024, 3026, 3027, 3028, 3031) | `attrs.language = 10,20`: **owner to confirm** the team serves clients in Greek and English |",
         "| `external_id` stable; removing it deletes the ad; new IDs are moderated as new ads | OFFICIAL | ledger + plan.py (STEP 10) |",
         "| Status for new ads: only `active`; `archive` / `remove` only for existing ads | OFFICIAL | catalog_proposed: active, publish false |",
         "| `last_update` yyyy-mm-dd h:m:s, unchanged = ad not re-processed | OFFICIAL | STEP 10 |",
         "| Greek first, then English; no Arabic | INTERNAL (owner) | `check_ad` |",
         "| Title 50–70 chars | INTERNAL | `check_ad` |",
         "| No city names in titles (no per-city copies) | INTERNAL (decline history) | `CITY_WORDS` |",
         "| No phone, e-mail, link, WhatsApp; no \"Bazaraki\" in the description | INTERNAL | `check_ad` |",
         "| Claims only from the registry; prohibited list (26 years, guarantee, free, licensed, …) | INTERNAL | `UNSUBSTANTIATED` + registry prohibited |",
         "| Stock photos: illustrative note required; never \"our work/projects\" | INTERNAL (D-028) | `STOCK_AS_OWN`, `PHOTO_NOTE_*` |",
         "| Price only from rates.json via price_meta | INTERNAL | `EURO` amounts must equal the approved price |",
         "| Greek and English carry the same facts | INTERNAL | `parity_problems` (item counts + numbers) |",
         "", "## Per ad", "", "| Service | Status | EN title chars | Description chars | Images | Problems |", "|---|---|---|---|---|---|"]
    for a in ads:
        C.append(f"| {a['service_key']} | {a['status']} | {len(a['title_en'])} | {len(a['description'])} | {len(a.get('images', []))} | {len(a['problems'])} |")
    _w(ae.ADS / "BAZARAKI_COMPLIANCE_CHECK.md", "\n".join(C) + "\n")

    # DUPLICATE_CHECK_REPORT.md
    D = ["# Duplicate check report (STEP 8, 2026-10-03)", "",
         "Checks:",
         "- (1) only one ad per service",
         "- (2) title and service-text similarity between all drafts (Jaccard ≥ 0.50 → reject)",
         "- (3) EN title against the 31 live ad titles (≥ 0.50 → reject, unless the live ad belongs to the same service and is planned for replacement)",
         "- (4) no city in the title",
         "", "**Limitation:** the 31 live ads are compared by **title**. Their full descriptions are not saved locally yet (D-015 download pending).", "",
         f"**Rejections:** {len(result['duplicates'])}", ""]
    D += [f"- {d}" for d in result["duplicates"]] or ["- none"]
    D += ["", "## Highest draft-to-draft similarities", "", "| A | B | title | text |", "|---|---|---|---|"]
    full = [a for a in ads if a.get("sections")]
    pairs = []
    for i, a in enumerate(full):
        for b in full[i + 1:]:
            body = lambda x: ae._words(ae.core_text(x["sections"]["en"]) + " " + ae.core_text(x["sections"]["el"]))
            pairs.append((ae._jac(ae._words(a["title_en"]), ae._words(b["title_en"])), ae._jac(body(a), body(b)), a["service_key"], b["service_key"]))
    for tj, bj, x, y in sorted(pairs, key=lambda p: -max(p[0], p[1]))[:10]:
        D.append(f"| {x} | {y} | {tj:.2f} | {bj:.2f} |")
    D += ["", "## Live ads per service (to be replaced in the transition, wave 3)", ""]
    for a in ads:
        for lid, t, j in a.get("live_conflicts", []):
            D.append(f"- {a['service_key']} ← live {lid} \"{t}\" (title similarity {j})")
    _w(ae.ADS / "DUPLICATE_CHECK_REPORT.md", "\n".join(D) + "\n")
